# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='contract_duration',
            field=models.IntegerField(default=4),
        ),
    ]
