# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0002_contracts_contract_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='date_signed_off',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='contract',
            field=models.ManyToManyField(blank=True, null=True, to='crew.Contracts'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='temp'),
        ),
        migrations.AlterField(
            model_name='presentrank',
            name='date_promoted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
