# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0003_auto_20170609_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contract',
            field=models.ManyToManyField(blank=True, to='crew.Contracts'),
        ),
    ]
