# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0004_auto_20170609_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='contract',
        ),
        migrations.AddField(
            model_name='person',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crew.Contracts'),
        ),
    ]
