# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0006_auto_20170609_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('owner', models.CharField(blank=True, max_length=200)),
                ('managed', models.CharField(choices=[('Y', 'OWN VESSEL'), ('N', 'OTHER COMPANY')], max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='vessels',
            name='deadweight',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vessels',
            name='kwh',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vessels',
            name='type',
            field=models.CharField(blank=True, choices=[('Oil', 'Oil Tanker'), ('Chem', 'Chemical Tanker'), ('Bulk', 'Bulk Carrier'), ('Gas', 'Gas Carrier')], max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=200),
        ),
        migrations.AlterField(
            model_name='vessels',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vessels',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crew.Company'),
            preserve_default=False,
        ),
    ]
