# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0008_auto_20170614_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentrank',
            name='rank',
        ),
        migrations.AlterField(
            model_name='person',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Rank'),
        ),
        migrations.DeleteModel(
            name='PresentRank',
        ),
    ]
