# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0009_auto_20170614_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewManagementCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phome', models.CharField(blank=True, max_length=200)),
                ('department_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Departments')),
            ],
        ),
        migrations.CreateModel(
            name='OperationsManagementCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phome', models.CharField(blank=True, max_length=200)),
                ('department_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Departments')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imo_no', models.IntegerField(null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyManagementCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phome', models.CharField(blank=True, max_length=200)),
                ('department_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Departments')),
            ],
        ),
        migrations.CreateModel(
            name='Seatime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signed_on', models.DateField()),
                ('date_signed_off', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Person')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalManagementCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phome', models.CharField(blank=True, max_length=200)),
                ('department_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Departments')),
            ],
        ),
        migrations.CreateModel(
            name='VesselType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='vessels',
            name='company',
        ),
        migrations.RemoveField(
            model_name='vessels',
            name='type',
        ),
        migrations.AddField(
            model_name='vessels',
            name='managed',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='Y', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AddField(
            model_name='seatime',
            name='vessel_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Vessels'),
        ),
        migrations.AddField(
            model_name='vessels',
            name='crew_management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crew.CrewManagementCompany'),
        ),
        migrations.AddField(
            model_name='vessels',
            name='operations_management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crew.OperationsManagementCompany'),
        ),
        migrations.AddField(
            model_name='vessels',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crew.Owner'),
        ),
        migrations.AddField(
            model_name='vessels',
            name='safety_management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crew.SafetyManagementCompany'),
        ),
        migrations.AddField(
            model_name='vessels',
            name='vessel_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crew.VesselType'),
            preserve_default=False,
        ),
    ]
