# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0010_auto_20170614_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessels',
            name='flag',
            field=models.CharField(default='Liberia', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vessels',
            name='gross_tonnage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vessels',
            name='net_tonnage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vessels',
            name='official_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vessels',
            name='port_of_registery',
            field=models.CharField(default='Monrovia', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vessels',
            name='rpm',
            field=models.IntegerField(null=True),
        ),
    ]
