# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0011_auto_20170614_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField()),
                ('date_expired', models.DateField(blank=True, null=True)),
                ('contract_duration', models.IntegerField(default=4)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Person')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Rank')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Vessels')),
            ],
        ),
        migrations.CreateModel(
            name='WageScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Rank')),
            ],
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='contract_rank',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='person',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='vessel',
        ),
        migrations.AddField(
            model_name='seatime',
            name='rank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crew.Rank'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Contracts',
        ),
        migrations.AddField(
            model_name='contract',
            name='wage_scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.WageScale'),
        ),
    ]
