# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0013_auto_20170614_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crewmanagementcompany',
            name='department_type',
        ),
        migrations.AddField(
            model_name='crewmanagementcompany',
            name='department_type',
            field=models.ManyToManyField(to='crew.Departments'),
        ),
        migrations.RemoveField(
            model_name='operationsmanagementcompany',
            name='department_type',
        ),
        migrations.AddField(
            model_name='operationsmanagementcompany',
            name='department_type',
            field=models.ManyToManyField(to='crew.Departments'),
        ),
        migrations.RemoveField(
            model_name='safetymanagementcompany',
            name='department_type',
        ),
        migrations.AddField(
            model_name='safetymanagementcompany',
            name='department_type',
            field=models.ManyToManyField(to='crew.Departments'),
        ),
        migrations.RemoveField(
            model_name='technicalmanagementcompany',
            name='department_type',
        ),
        migrations.AddField(
            model_name='technicalmanagementcompany',
            name='department_type',
            field=models.ManyToManyField(to='crew.Departments'),
        ),
    ]
