# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0015_auto_20170614_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='department_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
