# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0016_departments_department_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessels',
            name='bhp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vessels',
            name='official_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
