# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0017_auto_20170614_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessels',
            name='technical_management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crew.TechnicalManagementCompany'),
        ),
    ]
