# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0018_vessels_technical_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewCertificateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=200)),
                ('national_cert', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=100)),
                ('flag_cert', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=100)),
                ('company_required', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=100)),
                ('renewal_required', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=100)),
                ('paid_for_by', models.CharField(choices=[('CREW', 'CREW'), ('COMPANY', 'COMPANY')], max_length=200)),
                ('reminder_required', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=10)),
                ('required_for_ranks', models.ManyToManyField(to='crew.Rank')),
            ],
        ),
        migrations.CreateModel(
            name='CrewCertificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField()),
                ('date_expiry', models.DateField(blank=True, null=True)),
                ('institute_name', models.CharField(blank=True, max_length=200)),
                ('issued_place', models.CharField(blank=True, max_length=200)),
                ('certificate_no', models.IntegerField(default=0)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.CrewCertificateList')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Person')),
            ],
        ),
    ]
