# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0019_crewcertificatelist_crewcertificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewcertificates',
            name='certificate_no',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
