# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0020_auto_20170615_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatime',
            name='date_signed_off',
            field=models.DateField(blank=True, null=True),
        ),
    ]
