# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0021_auto_20170616_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='country_of_birth',
            field=models.CharField(default='India', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=models.CharField(default='Indian', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='place_of_birth',
            field=models.CharField(default='Mangalore', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rank',
            name='display_rank_priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
