# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0023_auto_20170618_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='rank_short_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
