# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-29 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0024_rank_rank_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='crew_photos'),
        ),
    ]
