# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-02 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0025_auto_20170629_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='contract_duration',
            new_name='contract_duration_in_months',
        ),
        migrations.AddField(
            model_name='crewcertificates',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='crew_certificates'),
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='crew_resume'),
        ),
        migrations.AlterField(
            model_name='person',
            name='key_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
