# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0026_auto_20170702_1314'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seatime',
            unique_together=set([('date_signed_on', 'date_signed_off', 'person')]),
        ),
    ]
