# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0028_auto_20170703_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewcertificatelist',
            name='certificate_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='rank',
            name='display_rank_priority',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='rank',
            name='rank_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Departments', unique=True),
        ),
        migrations.AlterField(
            model_name='rank',
            name='rank_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rank',
            name='rank_short_name',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='vessels',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='vessels',
            name='imo_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='vessels',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='vessels',
            name='official_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wagescale',
            name='level',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together=set([('date_started', 'person'), ('date_expired', 'person'), ('date_started', 'date_expired', 'person')]),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('first_name', 'last_name')]),
        ),
    ]
