# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0030_auto_20170704_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewmanagementcompany',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operationsmanagementcompany',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='safetymanagementcompany',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='technicalmanagementcompany',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
