# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0031_auto_20170704_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_joined_company',
            field=models.DateField(blank=True, null=True),
        ),
    ]
