# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0032_person_date_joined_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_duration_in_months',
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_expired',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
