# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0035_incompatiblewith'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incompatiblewith',
            name='notcompatible',
        ),
        migrations.AddField(
            model_name='person',
            name='incompatible_with',
            field=models.ManyToManyField(related_name='_person_incompatible_with_+', to='crew.Person'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_expired',
            field=models.DateField(verbose_name='Date Contract Ends'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_started',
            field=models.DateField(verbose_name='Date Contract Started'),
        ),
        migrations.AlterField(
            model_name='crewcertificatelist',
            name='certificate_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Certificate Name'),
        ),
        migrations.AlterField(
            model_name='crewcertificatelist',
            name='company_required',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=100, verbose_name='Company Course'),
        ),
        migrations.AlterField(
            model_name='crewcertificatelist',
            name='flag_cert',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=100, verbose_name='Flag Issued'),
        ),
        migrations.AlterField(
            model_name='crewcertificatelist',
            name='national_cert',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=100, verbose_name='Govt Issued'),
        ),
        migrations.AlterField(
            model_name='crewcertificatelist',
            name='paid_for_by',
            field=models.CharField(choices=[('CREW', 'CREW'), ('COMPANY', 'COMPANY')], max_length=200, verbose_name='Paid By'),
        ),
        migrations.AlterField(
            model_name='crewcertificatelist',
            name='reminder_required',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=10, verbose_name='Reminder Required'),
        ),
        migrations.AlterField(
            model_name='crewcertificatelist',
            name='renewal_required',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=100, verbose_name='Renewal Required'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True, verbose_name='Residence Address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='country_of_birth',
            field=models.CharField(max_length=200, verbose_name='Country Of Birth'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_joined_company',
            field=models.DateField(blank=True, null=True, verbose_name='Date Join Organisation'),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=200, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='key_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Unique Company No'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nationality',
            field=models.CharField(max_length=200, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='crew_photos', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='place_of_birth',
            field=models.CharField(max_length=200, verbose_name='Place of Birth'),
        ),
        migrations.AlterField(
            model_name='person',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='crew_resume', verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='person',
            name='salutation',
            field=models.CharField(max_length=10, verbose_name='Salutation'),
        ),
        migrations.AlterField(
            model_name='seatime',
            name='date_signed_off',
            field=models.DateField(blank=True, null=True, verbose_name='Date Signed Off'),
        ),
        migrations.AlterField(
            model_name='seatime',
            name='date_signed_on',
            field=models.DateField(verbose_name='Date Signed On'),
        ),
        migrations.DeleteModel(
            name='IncompatibleWith',
        ),
    ]
