# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0036_auto_20170731_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='incompatible_with',
            field=models.ManyToManyField(blank=True, related_name='_person_incompatible_with_+', to='crew.Person'),
        ),
    ]
