# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0039_auto_20170731_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_expired',
            field=models.DateField(help_text='YYYY-MM-DD', verbose_name='Date Contract Ends'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_started',
            field=models.DateField(help_text='YYYY-MM-DD', verbose_name='Date Contract Started'),
        ),
        migrations.AlterField(
            model_name='crewcertificates',
            name='date_expiry',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='crewcertificates',
            name='date_issued',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_joined_company',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True, verbose_name='Date Join Organisation'),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(help_text='YYYY-MM-DD', verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='seatime',
            name='date_signed_off',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True, verbose_name='Date Signed Off'),
        ),
        migrations.AlterField(
            model_name='seatime',
            name='date_signed_on',
            field=models.DateField(help_text='YYYY-MM-DD', verbose_name='Date Signed On'),
        ),
    ]
