# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0042_auto_20170731_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('crew.add_person', 'crew.change_person'),)},
        ),
    ]
