# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0043_auto_20170802_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
    ]
